package dev.sovarix.core

/**
 * 4 Core Product States of the SOVARIX System Intelligence:
 * AWARE -> Quiet observation under stable, nominal device operation.
 * ALERT -> Thermal or workload trend rising meaningfully.
 * PROTECT -> Active self-mitigation / Auto-Cool reducing SOVARIX load.
 * RECOVERY -> Device returning toward normal baseline after thermal stress.
 */
enum class ProductState(val label: String, val description: String) {
    AWARE("AWARE", "Quietly observing physical device telemetry"),
    ALERT("ALERT", "Thermal or workload trend rising meaningfully"),
    PROTECT("PROTECT", "Thermal Shield active — reducing internal workload"),
    RECOVERY("RECOVERY", "Device temperature returning toward normal baseline")
}

/**
 * User-selected high-level Device Goals for Phone Autopilot:
 * GOAL -> CURRENT STATE -> CONSTRAINTS -> POSSIBLE ACTIONS -> SIMULATE -> SELECT PERMITTED ACTION -> ACT -> VERIFY
 */
enum class DeviceGoal(val title: String, val subtitle: String) {
    KEEP_PHONE_COOL("Keep my phone cool", "Aggressive early thermal self-throttling & proactive cooling notifications"),
    PRESERVE_BATTERY("Preserve battery", "Minimizes sensor sampling and screen processing to extend battery endurance"),
    STABLE_GAMING("Maintain stable gaming performance", "Balances capture buffer and telemetry to avoid thermal throttling during gaming"),
    REDUCE_OVERHEAD("Reduce SOVARIX overhead", "Enforces minimal background compute and halts Local AI when idle"),
    PRIORITIZE_RECORDING("Prioritize recording", "Maintains full-fidelity media buffer unless hardware thermal limits are reached")
}

/**
 * Legitimate, safe self-governance actions permitted on standard Android devices.
 * SOVARIX never claims unauthorized control of CPU/GPU voltages or kernel thermal governors.
 */
enum class AutopilotAction(val actionName: String, val description: String) {
    THROTTLE_SOVARIX_SENSORS("Throttle Sensors", "Decrease sensor sampling frequency to conserve power"),
    PAUSE_VIDEO_BUFFER("Pause Video Buffer", "Pause rolling video buffer to drop memory and CPU bandwidth"),
    SUSPEND_LOCAL_AI("Suspend Local AI", "Halt on-device natural language inference"),
    SWITCH_ECO_GOVERNOR("Switch to ECO Mode", "Set ResourceGovernor to low-power budget"),
    ALERT_USER_THERMAL("Alert User", "Dispatch rate-limited thermal warning notification"),
    RECOMMEND_REDUCE_BRIGHTNESS("Recommend Dimming", "Recommend reducing screen brightness to combat heat"),
    NO_ACTION_REQUIRED("Nominal Operation", "System is operating within target goal boundaries")
}

/**
 * Decision generated by the Autopilot Decision Engine.
 */
data class AutopilotDecision(
    val goal: DeviceGoal,
    val productState: ProductState,
    val permittedActions: List<AutopilotAction>,
    val rationale: String,
    val simulatedTempDeltaC: Double? = null,
    val simulatedBatterySavingPctPerHour: Double? = null,
    val timestamp: Long = System.currentTimeMillis()
)

/**
 * Autopilot Decision Engine:
 * Translates DeviceGoal + Current TwinState into legitimate, verified self-governance actions.
 */
object AutopilotDecisionEngine {

    fun evaluate(
        state: TwinState,
        goal: DeviceGoal,
        behaviorModel: DeviceBehaviorModel
    ): AutopilotDecision {
        val temp = state.temperature ?: 37.0
        val thermalStatus = state.thermalState ?: 0
        val headroom = state.thermalHeadroom ?: 0.5
        val isGaming = state.gamingState || state.workload == Workload.GAMING
        val isCharging = state.chargingState == true

        // Determine product state
        val productState = when {
            thermalStatus >= 3 || temp >= 42.0 || (state.autoCoolDecision?.strategy?.level ?: 0) >= 2 -> ProductState.PROTECT
            (state.autoCoolDecision?.strategy?.level ?: 0) > 0 && (state.thermalTrend?.isCooling == true || (state.thermalTrend?.temperatureVelocity ?: 0.0) < -0.1) -> ProductState.RECOVERY
            thermalStatus >= 1 || temp >= 39.0 || (state.thermalTrend?.isRisingFast == true) -> ProductState.ALERT
            else -> ProductState.AWARE
        }

        val actions = mutableListOf<AutopilotAction>()
        val rationaleBuilder = StringBuilder()

        when (goal) {
            DeviceGoal.KEEP_PHONE_COOL -> {
                if (productState == ProductState.PROTECT || productState == ProductState.ALERT) {
                    actions += AutopilotAction.THROTTLE_SOVARIX_SENSORS
                    actions += AutopilotAction.PAUSE_VIDEO_BUFFER
                    actions += AutopilotAction.SUSPEND_LOCAL_AI
                    actions += AutopilotAction.SWITCH_ECO_GOVERNOR
                    actions += AutopilotAction.ALERT_USER_THERMAL
                    if (isCharging) {
                        actions += AutopilotAction.RECOMMEND_REDUCE_BRIGHTNESS
                    }
                    rationaleBuilder.append("Aggressive cooling requested: Auto-Cool active and internal workload minimized to avoid thermal throttling.")
                } else {
                    actions += AutopilotAction.NO_ACTION_REQUIRED
                    rationaleBuilder.append("Device temperature ($temp°C) is cool and nominal.")
                }
            }

            DeviceGoal.PRESERVE_BATTERY -> {
                actions += AutopilotAction.SWITCH_ECO_GOVERNOR
                actions += AutopilotAction.THROTTLE_SOVARIX_SENSORS
                if (state.battery?.let { it < 20.0 } == true) {
                    actions += AutopilotAction.PAUSE_VIDEO_BUFFER
                    actions += AutopilotAction.SUSPEND_LOCAL_AI
                    rationaleBuilder.append("Battery is below 20%: all non-essential intelligence paused.")
                } else {
                    rationaleBuilder.append("Battery preservation active: operating in lightweight ECO telemetry mode.")
                }
            }

            DeviceGoal.STABLE_GAMING -> {
                if (isGaming) {
                    if (productState == ProductState.PROTECT) {
                        actions += AutopilotAction.THROTTLE_SOVARIX_SENSORS
                        actions += AutopilotAction.SUSPEND_LOCAL_AI
                        actions += AutopilotAction.PAUSE_VIDEO_BUFFER
                        actions += AutopilotAction.ALERT_USER_THERMAL
                        rationaleBuilder.append("Gaming thermal rise detected: throttling internal background work to safeguard frame rate stability.")
                    } else {
                        actions += AutopilotAction.NO_ACTION_REQUIRED
                        rationaleBuilder.append("Gaming session stable with adequate thermal headroom.")
                    }
                } else {
                    actions += AutopilotAction.NO_ACTION_REQUIRED
                    rationaleBuilder.append("Standing by for gaming session launch.")
                }
            }

            DeviceGoal.REDUCE_OVERHEAD -> {
                actions += AutopilotAction.SWITCH_ECO_GOVERNOR
                actions += AutopilotAction.THROTTLE_SOVARIX_SENSORS
                actions += AutopilotAction.SUSPEND_LOCAL_AI
                rationaleBuilder.append("Minimal overhead policy enforced: lowest possible CPU and memory footprint.")
            }

            DeviceGoal.PRIORITIZE_RECORDING -> {
                if (productState == ProductState.PROTECT && thermalStatus >= 3) {
                    actions += AutopilotAction.THROTTLE_SOVARIX_SENSORS
                    actions += AutopilotAction.ALERT_USER_THERMAL
                    rationaleBuilder.append("Critical thermal threshold reached: maintaining capture while cutting background sensor compute.")
                } else {
                    actions += AutopilotAction.NO_ACTION_REQUIRED
                    rationaleBuilder.append("High-fidelity highlight recording and video buffer prioritized.")
                }
            }
        }

        // Expected simulated impact from applying self-governance
        val simTempDelta = if (actions.contains(AutopilotAction.THROTTLE_SOVARIX_SENSORS)) -0.15 else 0.0
        val simBatterySaving = if (actions.contains(AutopilotAction.SWITCH_ECO_GOVERNOR)) 2.2 else 0.5

        return AutopilotDecision(
            goal = goal,
            productState = productState,
            permittedActions = actions,
            rationale = rationaleBuilder.toString(),
            simulatedTempDeltaC = simTempDelta,
            simulatedBatterySavingPctPerHour = simBatterySaving
        )
    }
}
